apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngx-deployment
  namespace: nginx
  annotations:
    kubernetes.io/change-cause: "Updating to alpine version"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels: 
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:alpine
        ports:
        - containerPort: 80
